const express = require('express');
const router = express.Router();
const inputController = require('../controllers/promptController');

// POST route to save input...
router.post('/create', inputController.createInput);
// GET route to fetch inputs...
router.get('/all', inputController.getInputs);
// DELETE route to delete input...
router.delete('/delete/:id', inputController.deletePrompt);

module.exports = router; //. Export the file to the router....
